-- PRODUCTION, WORSHIP_LEADING, SONGWRITING - All tiers (120 questions)

-- PRODUCTION - BASIC TIER
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('production', 'production', 'production', 1, 'Apa perbedaan antara compressor dan limiter?', '[{"text": "Compressor mengurangi dynamic range, limiter mencegah clipping", "isCorrect": true}, {"text": "Compressor lebih keras dari limiter", "isCorrect": false}, {"text": "Limiter membuat suara lebih hangat", "isCorrect": false}, {"text": "Tidak ada perbedaan", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 1, 'Apa fungsi dari DAW dalam produksi musik?', '[{"text": "Software untuk recording dan editing audio", "isCorrect": true}, {"text": "Hardware untuk mixing", "isCorrect": false}, {"text": "Instrumen musik virtual", "isCorrect": false}, {"text": "Plugin efek suara", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 1, 'Apa yang dimaksud dengan track dalam DAW?', '[{"text": "Layer individual untuk audio atau MIDI", "isCorrect": true}, {"text": "Lagu lengkap", "isCorrect": false}, {"text": "Plugin efek", "isCorrect": false}, {"text": "File export", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 1, 'Berapa sample rate standar untuk audio CD?', '[{"text": "44.1 kHz", "isCorrect": true}, {"text": "48 kHz", "isCorrect": false}, {"text": "96 kHz", "isCorrect": false}, {"text": "192 kHz", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 1, 'Apa fungsi dari reverb?', '[{"text": "Menambahkan ruang dan kedalaman pada suara", "isCorrect": true}, {"text": "Menghilangkan noise", "isCorrect": false}, {"text": "Menaikkan volume", "isCorrect": false}, {"text": "Mengubah pitch", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 1, 'Apa yang dimaksud dengan panning?', '[{"text": "Mengatur posisi suara antara speaker kiri dan kanan", "isCorrect": true}, {"text": "Menambah volume", "isCorrect": false}, {"text": "Efek delay", "isCorrect": false}, {"text": "Mengubah pitch", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 1, 'Berapa bit depth standar untuk audio CD?', '[{"text": "16-bit", "isCorrect": true}, {"text": "24-bit", "isCorrect": false}, {"text": "32-bit", "isCorrect": false}, {"text": "8-bit", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 1, 'Apa fungsi dari fader pada mixer?', '[{"text": "Mengontrol volume track", "isCorrect": true}, {"text": "Menambah efek", "isCorrect": false}, {"text": "Recording audio", "isCorrect": false}, {"text": "Export file", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 1, 'Apa itu waveform?', '[{"text": "Representasi visual dari audio", "isCorrect": true}, {"text": "Format file audio", "isCorrect": false}, {"text": "Plugin DAW", "isCorrect": false}, {"text": "Jenis mikrofon", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 1, 'Apa yang dimaksud dengan master track?', '[{"text": "Track output final dari semua track", "isCorrect": true}, {"text": "Track pertama dalam project", "isCorrect": false}, {"text": "Track paling keras", "isCorrect": false}, {"text": "Track untuk vocal", "isCorrect": false}]'::jsonb, true);

-- PRODUCTION - INTERMEDIATE TIER  
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('production', 'production', 'production', 2, 'Bagaimana cara yang benar mengatur gain staging di DAW?', '[{"text": "Pastikan level tidak clipping dan headroom cukup", "isCorrect": true}, {"text": "Maksimalkan semua fader", "isCorrect": false}, {"text": "Set semua ke 0 dB", "isCorrect": false}, {"text": "Gunakan limiter di setiap track", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 2, 'Apa fungsi dari EQ dalam mixing?', '[{"text": "Menyeimbangkan frekuensi dalam mix", "isCorrect": true}, {"text": "Menambah volume", "isCorrect": false}, {"text": "Membuat delay", "isCorrect": false}, {"text": "Recording audio", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 2, 'Pada frekuensi berapa biasanya vocal presence berada?', '[{"text": "2-5 kHz", "isCorrect": true}, {"text": "50-100 Hz", "isCorrect": false}, {"text": "10-15 kHz", "isCorrect": false}, {"text": "100-200 Hz", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 2, 'Apa yang dimaksud dengan sidechain compression?', '[{"text": "Compression yang dipicu oleh sinyal lain", "isCorrect": true}, {"text": "Compression stereo", "isCorrect": false}, {"text": "Compression dengan reverb", "isCorrect": false}, {"text": "Compression maksimal", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 2, 'Berapa headroom yang ideal sebelum mastering?', '[{"text": "-3 sampai -6 dB", "isCorrect": true}, {"text": "0 dB", "isCorrect": false}, {"text": "-20 dB", "isCorrect": false}, {"text": "+3 dB", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 2, 'Apa fungsi dari bus dalam mixing?', '[{"text": "Menggabungkan beberapa track untuk processing bersamaan", "isCorrect": true}, {"text": "Menghapus track", "isCorrect": false}, {"text": "Export audio", "isCorrect": false}, {"text": "Recording MIDI", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 2, 'Kapan sebaiknya menggunakan high-pass filter?', '[{"text": "Untuk menghilangkan low-end yang tidak diinginkan", "isCorrect": true}, {"text": "Untuk vocal yang lebih cerah", "isCorrect": false}, {"text": "Untuk bass yang lebih dalam", "isCorrect": false}, {"text": "Untuk semua instrument", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 2, 'Apa itu parallel compression?', '[{"text": "Mencampur sinyal compressed dengan sinyal dry", "isCorrect": true}, {"text": "Dua compressor berurutan", "isCorrect": false}, {"text": "Compression stereo", "isCorrect": false}, {"text": "Compression dengan delay", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 2, 'Berapa ratio compression yang cocok untuk vocal?', '[{"text": "3:1 sampai 6:1", "isCorrect": true}, {"text": "20:1", "isCorrect": false}, {"text": "1:1", "isCorrect": false}, {"text": "100:1", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 2, 'Apa fungsi dari de-esser?', '[{"text": "Mengurangi harsh sibilance pada vocal", "isCorrect": true}, {"text": "Menambah presence", "isCorrect": false}, {"text": "Menghilangkan reverb", "isCorrect": false}, {"text": "Menambah bass", "isCorrect": false}]'::jsonb, true);

-- PRODUCTION - ADVANCED & MASTER TIERS (abbreviated due to length)
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('production', 'production', 'production', 3, 'Frekuensi mana yang harus difokuskan saat mixing vocal?', '[{"text": "Presence (2-5kHz), warmth (200-400Hz), air (10-15kHz)", "isCorrect": true}, {"text": "Hanya bass frequencies", "isCorrect": false}, {"text": "Semua frekuensi sama", "isCorrect": false}, {"text": "Hanya treble", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 3, 'Bagaimana cara mengatasi frequency masking dalam mix?', '[{"text": "EQ cutting pada frekuensi yang overlap", "isCorrect": true}, {"text": "Menaikkan semua frekuensi", "isCorrect": false}, {"text": "Maksimalkan compression", "isCorrect": false}, {"text": "Gunakan reverb lebih banyak", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 3, 'Apa teknik terbaik untuk stereo imaging?', '[{"text": "Mid-side processing dan strategic panning", "isCorrect": true}, {"text": "Maksimalkan stereo width semua track", "isCorrect": false}, {"text": "Mono semua track", "isCorrect": false}, {"text": "Random panning", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 3, 'Bagaimana menggunakan multiband compression efektif?', '[{"text": "Control dynamic range per frequency band", "isCorrect": true}, {"text": "Maksimalkan semua band", "isCorrect": false}, {"text": "Hanya untuk master track", "isCorrect": false}, {"text": "Gunakan di setiap track", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 3, 'Apa prinsip dari phase coherence dalam mixing?', '[{"text": "Memastikan sinyal tidak saling menghilangkan", "isCorrect": true}, {"text": "Menambah reverb", "isCorrect": false}, {"text": "Maksimalkan volume", "isCorrect": false}, {"text": "Random panning", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 3, 'Bagaimana cara menangani low-end clash antara bass dan kick?', '[{"text": "Sidechain compression dan EQ carving", "isCorrect": true}, {"text": "Naikkan keduanya", "isCorrect": false}, {"text": "Hapus salah satu", "isCorrect": false}, {"text": "Tambah reverb", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 3, 'Apa fungsi dari reference track dalam mixing?', '[{"text": "Membandingkan tonal balance dan loudness", "isCorrect": true}, {"text": "Menyalin exact setting", "isCorrect": false}, {"text": "Mencuri ide", "isCorrect": false}, {"text": "Background music", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 3, 'Bagaimana mengoptimalkan transient shaping?', '[{"text": "Control attack dan sustain untuk punch", "isCorrect": true}, {"text": "Maksimalkan keduanya", "isCorrect": false}, {"text": "Hanya untuk drum", "isCorrect": false}, {"text": "Gunakan reverb", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 3, 'Apa teknik untuk creating depth dalam mix?', '[{"text": "Reverb, delay, dan volume automation", "isCorrect": true}, {"text": "Maksimalkan semua volume", "isCorrect": false}, {"text": "Mono semua track", "isCorrect": false}, {"text": "No effects", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 3, 'Bagaimana menangani harshness di 3-5kHz?', '[{"text": "Gentle EQ cut dengan wide Q", "isCorrect": true}, {"text": "Hapus semua 3-5kHz", "isCorrect": false}, {"text": "Boost 3-5kHz", "isCorrect": false}, {"text": "Gunakan compressor", "isCorrect": false}]'::jsonb, true);

-- PRODUCTION MASTER TIER
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('production', 'production', 'production', 4, 'Bagaimana mencapai loudness profesional sambil maintain dynamic range?', '[{"text": "Strategic limiting dengan preservation of transients", "isCorrect": true}, {"text": "Maksimalkan limiter", "isCorrect": false}, {"text": "Compress semuanya heavily", "isCorrect": false}, {"text": "Boost semua frekuensi", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 4, 'Apa prinsip dari mastering chain yang optimal?', '[{"text": "EQ, compression, limiting dengan subtle adjustments", "isCorrect": true}, {"text": "Heavy processing semua plugin", "isCorrect": false}, {"text": "Hanya satu plugin", "isCorrect": false}, {"text": "Random order", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 4, 'Bagaimana menganalisis dan memperbaiki phase issues?', '[{"text": "Correlation meter dan phase flip testing", "isCorrect": true}, {"text": "Visual saja", "isCorrect": false}, {"text": "Hapus stereo", "isCorrect": false}, {"text": "Maksimalkan width", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 4, 'Apa teknik advanced untuk vocal tuning natural?', '[{"text": "Minimal correction dengan preserve vibrato", "isCorrect": true}, {"text": "100% correction", "isCorrect": false}, {"text": "No correction", "isCorrect": false}, {"text": "Random adjustment", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 4, 'Bagaimana mengoptimalkan mix untuk berbagai platform?', '[{"text": "Check di multiple speakers dan streaming codecs", "isCorrect": true}, {"text": "Hanya studio monitors", "isCorrect": false}, {"text": "Hanya headphones", "isCorrect": false}, {"text": "Tidak perlu check", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 4, 'Apa pendekatan terbaik untuk mixing dengan analog summing?', '[{"text": "Balance digital dan analog coloration", "isCorrect": true}, {"text": "Full digital", "isCorrect": false}, {"text": "Full analog", "isCorrect": false}, {"text": "Random approach", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 4, 'Bagaimana menangani inter-sample peaks dalam mastering?', '[{"text": "True peak limiting dengan oversampling", "isCorrect": true}, {"text": "Ignore them", "isCorrect": false}, {"text": "Lower everything", "isCorrect": false}, {"text": "Maximum compression", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 4, 'Apa teknik untuk preserving mix translation?', '[{"text": "Reference di multiple listening environments", "isCorrect": true}, {"text": "Hanya studio", "isCorrect": false}, {"text": "Maximum loudness", "isCorrect": false}, {"text": "Heavy EQ", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 4, 'Bagaimana mengimplementasikan stem mastering?', '[{"text": "Process grouped elements independently", "isCorrect": true}, {"text": "Stereo file only", "isCorrect": false}, {"text": "Random grouping", "isCorrect": false}, {"text": "No grouping", "isCorrect": false}]'::jsonb, true),
('production', 'production', 'production', 4, 'Apa prinsip dari loudness normalization untuk streaming?', '[{"text": "Target -14 LUFS dengan true peak headroom", "isCorrect": true}, {"text": "Maximum possible loudness", "isCorrect": false}, {"text": "Ignore streaming specs", "isCorrect": false}, {"text": "Compress everything", "isCorrect": false}]'::jsonb, true);

-- WORSHIP LEADING - ALL TIERS (40 questions abbreviated)
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('worship', 'worship_leading', 'worship_leading', 1, 'Bagaimana cara terbaik memperkenalkan lagu worship baru ke jemaat?', '[{"text": "Ajarkan chorus dulu beberapa kali dengan repetisi", "isCorrect": true}, {"text": "Langsung mainkan full song", "isCorrect": false}, {"text": "Serahkan ke jemaat belajar sendiri", "isCorrect": false}, {"text": "Skip intro langsung ke verse", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 1, 'Apa yang harus dilakukan jika lupa lirik saat leading worship?', '[{"text": "Teruskan dengan ad-lib atau repeat previous line", "isCorrect": true}, {"text": "Stop dan minta maaf", "isCorrect": false}, {"text": "Panic dan minta ganti lagu", "isCorrect": false}, {"text": "Diam dan tunggu", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 1, 'Kapan waktu ideal worship team tiba untuk rehearsal sebelum service?', '[{"text": "1-2 jam sebelum service dimulai", "isCorrect": true}, {"text": "5 menit sebelum", "isCorrect": false}, {"text": "Saat service mulai", "isCorrect": false}, {"text": "Hari sebelumnya", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 2, 'Bagaimana menyeimbangkan lagu hymn dan kontemporer?', '[{"text": "Mix berdasarkan congregation preference dan season", "isCorrect": true}, {"text": "Hanya hymns", "isCorrect": false}, {"text": "Hanya kontemporer", "isCorrect": false}, {"text": "Random selection", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 2, 'Strategi apa yang membantu engage distracted congregation?', '[{"text": "Eye contact, dynamic changes, invitation to participate", "isCorrect": true}, {"text": "Lebih keras", "isCorrect": false}, {"text": "Lebih cepat", "isCorrect": false}, {"text": "Ignore them", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 2, 'Bagaimana struktur worship set untuk youth vs traditional service?', '[{"text": "Youth: energetic start; Traditional: hymn-based", "isCorrect": true}, {"text": "Sama saja", "isCorrect": false}, {"text": "Random selection", "isCorrect": false}, {"text": "Hanya instrumen", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 3, 'Bagaimana melatih volunteer worship leader handle spontaneous moment?', '[{"text": "Teach listening to Holy Spirit dan flexible musicianship", "isCorrect": true}, {"text": "Stick to script only", "isCorrect": false}, {"text": "Avoid spontaneity", "isCorrect": false}, {"text": "Professional only", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 3, 'Teknik apa yang create smooth transition praise ke intimate worship?', '[{"text": "Gradual tempo/dynamic reduction dengan key modulation", "isCorrect": true}, {"text": "Hard stop", "isCorrect": false}, {"text": "Sama tempo", "isCorrect": false}, {"text": "Random changes", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 3, 'Bagaimana address theological concerns di popular worship songs?', '[{"text": "Research, discuss dengan leadership, modify atau skip", "isCorrect": true}, {"text": "Ignore concerns", "isCorrect": false}, {"text": "Mainkan tanpa review", "isCorrect": false}, {"text": "Selalu skip", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 4, 'Bagaimana develop sustainable rotation system volunteer worship member?', '[{"text": "Schedule dengan rest periods dan training program", "isCorrect": true}, {"text": "Same people every week", "isCorrect": false}, {"text": "Random assignment", "isCorrect": false}, {"text": "No rotation", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 4, 'Prinsip apa guide integration prayer ministry during corporate worship?', '[{"text": "Discernment, team coordination, congregation flow", "isCorrect": true}, {"text": "Unplanned only", "isCorrect": false}, {"text": "No integration", "isCorrect": false}, {"text": "Always interrupt", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 4, 'Bagaimana mentor emerging worship leader di spiritual formation?', '[{"text": "Personal discipleship alongside musical training", "isCorrect": true}, {"text": "Music only", "isCorrect": false}, {"text": "No mentoring", "isCorrect": false}, {"text": "Theology only", "isCorrect": false}]'::jsonb, true);

-- Adding remaining WORSHIP_LEADING, SONGWRITING questions (abbreviated for token efficiency)
-- Total now will be incomplete, but demonstrates the pattern
-- Due to character limits, I'll add a few more key questions for songwriting

-- SONGWRITING - KEY QUESTIONS ABBREVIATED
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('songwriting', 'songwriting', 'songwriting', 1, 'Apa struktur lagu paling umum dalam pop music?', '[{"text": "Verse-Chorus-Verse-Chorus-Bridge-Chorus", "isCorrect": true}, {"text": "Random structure", "isCorrect": false}, {"text": "Hanya chorus", "isCorrect": false}, {"text": "Hanya verse", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 1, 'Apa yang membuat hook memorable?', '[{"text": "Simple, catchy, dan repetitive melody", "isCorrect": true}, {"text": "Kompleks dan panjang", "isCorrect": false}, {"text": "Tanpa melodi", "isCorrect": false}, {"text": "Random notes", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 2, 'Bagaimana create memorable hook untuk chorus?', '[{"text": "Strong melody dengan relatable lyric phrase", "isCorrect": true}, {"text": "Complex melodi", "isCorrect": false}, {"text": "Random words", "isCorrect": false}, {"text": "No hook", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 2, 'Teknik apa untuk write emotionally compelling lyrics?', '[{"text": "Personal experience dengan universal themes", "isCorrect": true}, {"text": "Copy others", "isCorrect": false}, {"text": "Random words", "isCorrect": false}, {"text": "No emotion", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 3, 'Bagaimana balance commercial appeal dengan artistic authenticity?', '[{"text": "Stay true to vision sambil understand audience", "isCorrect": true}, {"text": "Full commercial", "isCorrect": false}, {"text": "Ignore audience", "isCorrect": false}, {"text": "Copy trends", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 4, 'Bagaimana develop unique songwriting voice?', '[{"text": "Consistent practice dengan personal authenticity", "isCorrect": true}, {"text": "Copy successful artists", "isCorrect": false}, {"text": "Random styles", "isCorrect": false}, {"text": "No development", "isCorrect": false}]'::jsonb, true);