-- MUSIC THEORY - All 4 tiers (40 questions total)
-- Theory BASIC TIER
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('theory', 'theory', 'theory', 1, 'Apa arti dari time signature 4/4?', '[{"text": "4 ketukan per bar, quarter note mendapat 1 ketukan", "isCorrect": true}, {"text": "4 bar per lagu", "isCorrect": false}, {"text": "4 nada per chord", "isCorrect": false}, {"text": "4 instrumen dalam band", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 1, 'Berapa jumlah nada dalam tangga nada mayor?', '[{"text": "5 nada", "isCorrect": false}, {"text": "6 nada", "isCorrect": false}, {"text": "7 nada", "isCorrect": true}, {"text": "8 nada", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 1, 'Apa yang dimaksud dengan oktaf?', '[{"text": "Interval 8 nada", "isCorrect": true}, {"text": "8 beat dalam bar", "isCorrect": false}, {"text": "8 chord dalam progresi", "isCorrect": false}, {"text": "8 instrumen", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 1, 'Nada apa yang berada di antara C dan E?', '[{"text": "D", "isCorrect": true}, {"text": "F", "isCorrect": false}, {"text": "G", "isCorrect": false}, {"text": "B", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 1, 'Apa simbol # pada notasi musik?', '[{"text": "Sharp - menaikkan nada setengah langkah", "isCorrect": true}, {"text": "Flat - menurunkan nada", "isCorrect": false}, {"text": "Natural - mengembalikan nada", "isCorrect": false}, {"text": "Rest - istirahat", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 1, 'Chord mayor terdiri dari interval apa?', '[{"text": "Root, major third, perfect fifth", "isCorrect": true}, {"text": "Root, minor third, fifth", "isCorrect": false}, {"text": "Hanya dua nada", "isCorrect": false}, {"text": "Empat nada berbeda", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 1, 'Apa fungsi dari treble clef?', '[{"text": "Menunjukkan nada-nada tinggi", "isCorrect": true}, {"text": "Menunjukkan nada rendah", "isCorrect": false}, {"text": "Menunjukkan tempo", "isCorrect": false}, {"text": "Menunjukkan volume", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 1, 'Berapa nilai ketukan dari whole note?', '[{"text": "1 ketukan", "isCorrect": false}, {"text": "2 ketukan", "isCorrect": false}, {"text": "3 ketukan", "isCorrect": false}, {"text": "4 ketukan", "isCorrect": true}]'::jsonb, true),
('theory', 'theory', 'theory', 1, 'Apa yang dimaksud dengan rest dalam musik?', '[{"text": "Istirahat/diam tidak membunyikan nada", "isCorrect": true}, {"text": "Bermain pelan", "isCorrect": false}, {"text": "Bermain keras", "isCorrect": false}, {"text": "Mengulangi bagian", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 1, 'Nada C ke C berikutnya disebut apa?', '[{"text": "Oktaf", "isCorrect": true}, {"text": "Skala", "isCorrect": false}, {"text": "Interval", "isCorrect": false}, {"text": "Chord", "isCorrect": false}]'::jsonb, true);

-- Theory INTERMEDIATE TIER
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('theory', 'theory', 'theory', 2, 'Bagaimana cara mengidentifikasi key dari chord progression?', '[{"text": "Analisis chord yang digunakan dan tonic chord", "isCorrect": true}, {"text": "Melihat tempo lagu", "isCorrect": false}, {"text": "Menghitung jumlah instrumen", "isCorrect": false}, {"text": "Mendengar volume", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 2, 'Apa perbedaan antara major dan minor chord?', '[{"text": "Major memiliki third yang lebih tinggi", "isCorrect": true}, {"text": "Major lebih keras", "isCorrect": false}, {"text": "Major lebih cepat", "isCorrect": false}, {"text": "Tidak ada perbedaan", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 2, 'Apa fungsi dari dominant chord (V) dalam progression?', '[{"text": "Menciptakan tension yang menuju ke tonic", "isCorrect": true}, {"text": "Mengakhiri lagu", "isCorrect": false}, {"text": "Memulai intro", "isCorrect": false}, {"text": "Menambah volume", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 2, 'Interval apa yang membentuk perfect fifth?', '[{"text": "7 semitone dari root", "isCorrect": true}, {"text": "5 semitone dari root", "isCorrect": false}, {"text": "3 semitone dari root", "isCorrect": false}, {"text": "12 semitone dari root", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 2, 'Apa yang dimaksud dengan relative minor?', '[{"text": "Minor key yang berbagi key signature dengan major", "isCorrect": true}, {"text": "Minor chord yang lebih kecil", "isCorrect": false}, {"text": "Tempo yang lebih lambat", "isCorrect": false}, {"text": "Volume yang lebih pelan", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 2, 'Bagaimana cara membaca chord symbol "Cmaj7"?', '[{"text": "C mayor dengan seventh mayor", "isCorrect": true}, {"text": "C minor dengan seventh", "isCorrect": false}, {"text": "C dengan 7 nada", "isCorrect": false}, {"text": "C dimainkan 7 kali", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 2, 'Apa fungsi dari time signature 3/4?', '[{"text": "3 ketukan per bar, waltz feel", "isCorrect": true}, {"text": "3 bar per section", "isCorrect": false}, {"text": "3 instrumen", "isCorrect": false}, {"text": "3 chord progression", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 2, 'Apa yang dimaksud dengan syncopation?', '[{"text": "Penekanan pada weak beat", "isCorrect": true}, {"text": "Bermain sangat cepat", "isCorrect": false}, {"text": "Volume yang keras", "isCorrect": false}, {"text": "Menggunakan banyak instrument", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 2, 'Circle of fifths digunakan untuk apa?', '[{"text": "Memahami hubungan antar key", "isCorrect": true}, {"text": "Menghitung tempo", "isCorrect": false}, {"text": "Mengatur volume", "isCorrect": false}, {"text": "Memilih instrumen", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 2, 'Apa perbedaan antara diatonic dan chromatic?', '[{"text": "Diatonic dalam satu key, chromatic menggunakan semua 12 nada", "isCorrect": true}, {"text": "Diatonic lebih keras", "isCorrect": false}, {"text": "Chromatic lebih lambat", "isCorrect": false}, {"text": "Tidak ada perbedaan", "isCorrect": false}]'::jsonb, true);

-- Theory ADVANCED TIER
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('theory', 'theory', 'theory', 3, 'Apa fungsi dari secondary dominant dalam harmonic progression?', '[{"text": "Dominant dari chord non-tonic untuk modulasi sementara", "isCorrect": true}, {"text": "Chord kedua dalam progresi", "isCorrect": false}, {"text": "Backup chord", "isCorrect": false}, {"text": "Chord yang jarang dipakai", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 3, 'Bagaimana modal interchange bekerja dalam komposisi?', '[{"text": "Meminjam chord dari parallel key", "isCorrect": true}, {"text": "Mengganti mode instrumen", "isCorrect": false}, {"text": "Mengubah tempo", "isCorrect": false}, {"text": "Menambah instrumen", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 3, 'Apa yang dimaksud dengan tritone substitution?', '[{"text": "Mengganti dominant chord dengan chord berjarak tritone", "isCorrect": true}, {"text": "Menggunakan tiga nada", "isCorrect": false}, {"text": "Bermain tiga kali", "isCorrect": false}, {"text": "Tempo tiga kali lipat", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 3, 'Bagaimana menganalisis voice leading dalam progression?', '[{"text": "Melihat gerakan setiap voice antar chord", "isCorrect": true}, {"text": "Menghitung jumlah vocal", "isCorrect": false}, {"text": "Mengatur volume vokal", "isCorrect": false}, {"text": "Memilih penyanyi", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 3, 'Apa fungsi dari augmented sixth chord?', '[{"text": "Pre-dominant chord dengan tension khusus", "isCorrect": true}, {"text": "Chord dengan 6 nada", "isCorrect": false}, {"text": "Chord dimainkan 6 kali", "isCorrect": false}, {"text": "Tempo 6/8", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 3, 'Bagaimana penerapan lydian mode dalam improvisasi?', '[{"text": "Menggunakan raised 4th untuk brightness", "isCorrect": true}, {"text": "Menggunakan 4 nada saja", "isCorrect": false}, {"text": "Tempo 4/4", "isCorrect": false}, {"text": "4 instrumen", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 3, 'Apa yang dimaksud dengan enharmonic equivalence?', '[{"text": "Nada berbeda nama tapi sama pitch", "isCorrect": true}, {"text": "Nada yang harmonis", "isCorrect": false}, {"text": "Instrumen yang mirip", "isCorrect": false}, {"text": "Chord yang sama", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 3, 'Bagaimana mengaplikasikan upper structure triads?', '[{"text": "Triad yang dibangun dari extension chord", "isCorrect": true}, {"text": "Chord di register tinggi", "isCorrect": false}, {"text": "Triad paling atas dalam progresi", "isCorrect": false}, {"text": "Struktur tiga layer", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 3, 'Apa prinsip dari negative harmony?', '[{"text": "Inversi interval seputar axis tonal", "isCorrect": true}, {"text": "Harmoni yang sedih", "isCorrect": false}, {"text": "Harmoni tanpa chord", "isCorrect": false}, {"text": "Volume negatif", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 3, 'Bagaimana polychord mempengaruhi harmoni?', '[{"text": "Dua chord dimainkan bersamaan untuk warna kompleks", "isCorrect": true}, {"text": "Banyak chord dalam lagu", "isCorrect": false}, {"text": "Chord yang panjang", "isCorrect": false}, {"text": "Chord dengan banyak nada", "isCorrect": false}]'::jsonb, true);

-- Theory MASTER TIER
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('theory', 'theory', 'theory', 4, 'Bagaimana modal interchange bekerja dalam komposisi jazz?', '[{"text": "Meminjam chord dari parallel modes untuk warna harmonis", "isCorrect": true}, {"text": "Mengganti mode instrumen", "isCorrect": false}, {"text": "Mengubah key signature", "isCorrect": false}, {"text": "Modulasi permanen", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 4, 'Apa pendekatan terbaik mengajarkan counterpoint kepada siswa?', '[{"text": "Dimulai dari species counterpoint hingga free counterpoint", "isCorrect": true}, {"text": "Langsung ke fugue", "isCorrect": false}, {"text": "Fokus pada harmoni modern", "isCorrect": false}, {"text": "Hindari Bach", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 4, 'Bagaimana menganalisis struktur sonata form?', '[{"text": "Exposition, development, recapitulation dengan tonal plan", "isCorrect": true}, {"text": "Intro, verse, chorus", "isCorrect": false}, {"text": "Hanya 3 bagian", "isCorrect": false}, {"text": "Struktur bebas", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 4, 'Apa prinsip dari twelve-tone technique Schoenberg?', '[{"text": "Semua 12 nada kromatis tanpa hierarki tonal", "isCorrect": true}, {"text": "Menggunakan 12 instrumen", "isCorrect": false}, {"text": "12 bar blues", "isCorrect": false}, {"text": "12/8 time signature", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 4, 'Bagaimana set theory digunakan dalam analisis musik modern?', '[{"text": "Mengidentifikasi pitch class sets dan transformasi", "isCorrect": true}, {"text": "Teori tentang stage setup", "isCorrect": false}, {"text": "Pengaturan band", "isCorrect": false}, {"text": "Teori amplifier", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 4, 'Apa fungsi dari Neapolitan sixth dalam harmoni klasik?', '[{"text": "Pre-dominant dengan lowered second scale degree", "isCorrect": true}, {"text": "Chord dari Italia", "isCorrect": false}, {"text": "Chord manis seperti es krim", "isCorrect": false}, {"text": "Chord untuk opera", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 4, 'Bagaimana quartal harmony berbeda dari tertian?', '[{"text": "Dibangun dari fourth intervals bukan thirds", "isCorrect": true}, {"text": "Menggunakan 4 nada", "isCorrect": false}, {"text": "4/4 time signature", "isCorrect": false}, {"text": "Empat instrumen", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 4, 'Apa teknik komposisi dari minimalism (Reich, Glass)?', '[{"text": "Repetisi pattern dengan gradual variation", "isCorrect": true}, {"text": "Musik yang sangat pendek", "isCorrect": false}, {"text": "Volume minimal", "isCorrect": false}, {"text": "Sedikit instrumen", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 4, 'Bagaimana menganalisis micro-timing dalam groove?', '[{"text": "Deviasi subtle dari quantized grid", "isCorrect": true}, {"text": "Waktu yang sangat pendek", "isCorrect": false}, {"text": "Volume mikro", "isCorrect": false}, {"text": "Instrumen kecil", "isCorrect": false}]'::jsonb, true),
('theory', 'theory', 'theory', 4, 'Apa prinsip dari spectralism dalam komposisi kontemporer?', '[{"text": "Harmoni berdasarkan overtone series natural", "isCorrect": true}, {"text": "Musik dengan banyak warna", "isCorrect": false}, {"text": "Visual dalam musik", "isCorrect": false}, {"text": "Analisis spektrum audio", "isCorrect": false}]'::jsonb, true);