-- Complete WORSHIP_LEADING questions (need 28 more to reach 40 total)
-- WORSHIP_LEADING - BASIC TIER (add 7 more)
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('worship', 'worship_leading', 'worship_leading', 1, 'Berapa lama idealnya durasi worship set?', '[{"text": "20-30 menit", "isCorrect": true}, {"text": "5 menit", "isCorrect": false}, {"text": "2 jam", "isCorrect": false}, {"text": "Tanpa batas", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 1, 'Apa yang penting saat memilih lagu worship?', '[{"text": "Sesuai tema dan mudah dinyanyikan jemaat", "isCorrect": true}, {"text": "Lagu terpopuler", "isCorrect": false}, {"text": "Lagu tercepat", "isCorrect": false}, {"text": "Random pilihan", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 1, 'Bagaimana memimpin worship dengan percaya diri?', '[{"text": "Persiapan matang dan fokus pada Tuhan", "isCorrect": true}, {"text": "Tidak perlu persiapan", "isCorrect": false}, {"text": "Fokus pada penampilan", "isCorrect": false}, {"text": "Hindari eye contact", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 1, 'Apa role dari worship leader?', '[{"text": "Memimpin jemaat dalam penyembahan kepada Tuhan", "isCorrect": true}, {"text": "Menghibur jemaat", "isCorrect": false}, {"text": "Menunjukkan skill musik", "isCorrect": false}, {"text": "Perform seperti konser", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 1, 'Bagaimana mengatur volume saat leading worship?', '[{"text": "Seimbangkan antara team dan congregation", "isCorrect": true}, {"text": "Maksimalkan volume", "isCorrect": false}, {"text": "Sangat pelan", "isCorrect": false}, {"text": "Random volume", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 1, 'Apa yang harus dilakukan sebelum service dimulai?', '[{"text": "Prayer dan sound check", "isCorrect": true}, {"text": "Langsung mulai tanpa persiapan", "isCorrect": false}, {"text": "Hanya prayer saja", "isCorrect": false}, {"text": "Tidak perlu apa-apa", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 1, 'Berapa lagu yang ideal dalam satu worship set?', '[{"text": "4-6 lagu", "isCorrect": true}, {"text": "1 lagu", "isCorrect": false}, {"text": "15 lagu", "isCorrect": false}, {"text": "Tidak ada patokan", "isCorrect": false}]'::jsonb, true);

-- WORSHIP_LEADING - INTERMEDIATE TIER (add 7 more)
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('worship', 'worship_leading', 'worship_leading', 2, 'Bagaimana menangani technical issue di tengah worship?', '[{"text": "Tetap tenang dan continue tanpa panik", "isCorrect": true}, {"text": "Stop semuanya", "isCorrect": false}, {"text": "Blame sound engineer", "isCorrect": false}, {"text": "Leave stage", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 2, 'Bagaimana membuat setlist yang flow dengan baik?', '[{"text": "Pertimbangkan tempo, key, dan tema progression", "isCorrect": true}, {"text": "Random song order", "isCorrect": false}, {"text": "Semua lagu cepat", "isCorrect": false}, {"text": "Semua lagu lambat", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 2, 'Apa yang dilakukan saat jemaat tidak responsive?', '[{"text": "Adjust dynamic, simplify, dan invite participation", "isCorrect": true}, {"text": "Lebih keras dan cepat", "isCorrect": false}, {"text": "Berhenti leading", "isCorrect": false}, {"text": "Kritik jemaat", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 2, 'Bagaimana coordinate dengan tech team?', '[{"text": "Clear communication dan rehearsal together", "isCorrect": true}, {"text": "No communication needed", "isCorrect": false}, {"text": "Mereka tahu sendiri", "isCorrect": false}, {"text": "Blame jika ada masalah", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 2, 'Kapan menggunakan spontaneous worship?', '[{"text": "Saat Holy Spirit leading dan congregation receptive", "isCorrect": true}, {"text": "Selalu spontaneous", "isCorrect": false}, {"text": "Tidak pernah", "isCorrect": false}, {"text": "Random timing", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 2, 'Bagaimana train new worship team members?', '[{"text": "Patient instruction dengan hands-on practice", "isCorrect": true}, {"text": "Langsung perform di service", "isCorrect": false}, {"text": "No training needed", "isCorrect": false}, {"text": "Kritik terus menerus", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 2, 'Apa yang dilakukan setelah worship service selesai?', '[{"text": "Debrief dengan team dan thank volunteers", "isCorrect": true}, {"text": "Langsung pulang", "isCorrect": false}, {"text": "Tidak perlu apa-apa", "isCorrect": false}, {"text": "Kritik semua orang", "isCorrect": false}]'::jsonb, true);

-- WORSHIP_LEADING - ADVANCED TIER (add 7 more)
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('worship', 'worship_leading', 'worship_leading', 3, 'Bagaimana develop worship culture dalam church?', '[{"text": "Consistent teaching, modeling, dan participation", "isCorrect": true}, {"text": "Performance excellence only", "isCorrect": false}, {"text": "Ignore culture", "isCorrect": false}, {"text": "Force participation", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 3, 'Bagaimana balance excellence dan accessibility?', '[{"text": "High quality yang tetap relatable dan participatory", "isCorrect": true}, {"text": "Excellence tanpa accessibility", "isCorrect": false}, {"text": "Simple without quality", "isCorrect": false}, {"text": "No balance needed", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 3, 'Bagaimana menangani conflict dalam worship team?', '[{"text": "Address privately dengan grace dan truth", "isCorrect": true}, {"text": "Public confrontation", "isCorrect": false}, {"text": "Ignore conflict", "isCorrect": false}, {"text": "Kick member immediately", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 3, 'Bagaimana integrate different age groups dalam worship?', '[{"text": "Varied song selection dengan accessible style", "isCorrect": true}, {"text": "Hanya satu demographic", "isCorrect": false}, {"text": "Separate completely", "isCorrect": false}, {"text": "Ignore older generation", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 3, 'Bagaimana prepare worship untuk special seasons?', '[{"text": "Thematic planning dengan appropriate song selection", "isCorrect": true}, {"text": "Same setlist always", "isCorrect": false}, {"text": "No preparation", "isCorrect": false}, {"text": "Random selection", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 3, 'Apa yang dilakukan saat Holy Spirit moves unexpectedly?', '[{"text": "Be flexible dan follow Spirit leading sensitively", "isCorrect": true}, {"text": "Stick to plan rigidly", "isCorrect": false}, {"text": "Ignore it", "isCorrect": false}, {"text": "End service", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 3, 'Bagaimana evaluate worship service effectiveness?', '[{"text": "Team feedback, spiritual fruit, congregation response", "isCorrect": true}, {"text": "Only attendance numbers", "isCorrect": false}, {"text": "Performance quality only", "isCorrect": false}, {"text": "No evaluation", "isCorrect": false}]'::jsonb, true);

-- WORSHIP_LEADING - MASTER TIER (add 7 more)
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('worship', 'worship_leading', 'worship_leading', 4, 'Bagaimana build multi-generational worship team?', '[{"text": "Intentional recruiting dengan diverse skill training", "isCorrect": true}, {"text": "Only young people", "isCorrect": false}, {"text": "Age segregation", "isCorrect": false}, {"text": "No diversity needed", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 4, 'Bagaimana shepherd worship volunteers spiritually?', '[{"text": "Regular discipleship dan spiritual care meetings", "isCorrect": true}, {"text": "Music only", "isCorrect": false}, {"text": "No shepherding", "isCorrect": false}, {"text": "Performance feedback only", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 4, 'Bagaimana develop sustainable worship ministry long-term?', '[{"text": "Leadership pipeline, rest cycles, spiritual health", "isCorrect": true}, {"text": "Work same people constantly", "isCorrect": false}, {"text": "No planning", "isCorrect": false}, {"text": "Hire all professionals", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 4, 'Bagaimana handle worship in multi-site church?', '[{"text": "Consistent vision dengan local contextualization", "isCorrect": true}, {"text": "Exact same everything", "isCorrect": false}, {"text": "Completely different", "isCorrect": false}, {"text": "No coordination", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 4, 'Apa prinsip training emerging worship leaders?', '[{"text": "Spiritual formation, technical skill, leadership development", "isCorrect": true}, {"text": "Technical skill only", "isCorrect": false}, {"text": "No training", "isCorrect": false}, {"text": "Performance focus", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 4, 'Bagaimana integrate arts team dalam worship ministry?', '[{"text": "Unified vision dengan coordinated planning", "isCorrect": true}, {"text": "Arts work separately", "isCorrect": false}, {"text": "No integration", "isCorrect": false}, {"text": "Music dominates", "isCorrect": false}]'::jsonb, true),
('worship', 'worship_leading', 'worship_leading', 4, 'Bagaimana create theology-rich worship experience?', '[{"text": "Doctrinally sound songs dengan biblical teaching", "isCorrect": true}, {"text": "Emotion only", "isCorrect": false}, {"text": "Ignore theology", "isCorrect": false}, {"text": "Entertainment focus", "isCorrect": false}]'::jsonb, true);

-- Complete SONGWRITING questions (need 34 more to reach 40 total)
-- SONGWRITING - BASIC TIER (add 8 more for total 10)
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('songwriting', 'songwriting', 'songwriting', 1, 'Apa bagian penting dalam intro lagu?', '[{"text": "Menarik perhatian dan set mood", "isCorrect": true}, {"text": "Harus panjang", "isCorrect": false}, {"text": "Tidak perlu intro", "isCorrect": false}, {"text": "Random sounds", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 1, 'Berapa chord yang umum dalam pop song?', '[{"text": "3-4 chord", "isCorrect": true}, {"text": "1 chord", "isCorrect": false}, {"text": "20 chord", "isCorrect": false}, {"text": "No chords", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 1, 'Apa fungsi dari verse dalam lagu?', '[{"text": "Menceritakan story dan develop tema", "isCorrect": true}, {"text": "Hanya background music", "isCorrect": false}, {"text": "Sama dengan chorus", "isCorrect": false}, {"text": "Tidak penting", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 1, 'Apa yang membuat chorus efektif?', '[{"text": "Catchy, memorable, dan emotional peak", "isCorrect": true}, {"text": "Complicated dan panjang", "isCorrect": false}, {"text": "Sulit dinyanyikan", "isCorrect": false}, {"text": "Random words", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 1, 'Berapa line umum dalam verse?', '[{"text": "4-8 line", "isCorrect": true}, {"text": "1 line", "isCorrect": false}, {"text": "50 line", "isCorrect": false}, {"text": "No lines", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 1, 'Apa fungsi dari bridge?', '[{"text": "Memberikan kontras dan perspektif baru", "isCorrect": true}, {"text": "Repeat chorus", "isCorrect": false}, {"text": "End song", "isCorrect": false}, {"text": "No purpose", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 1, 'Bagaimana mulai menulis lagu?', '[{"text": "Dengan melody, lyric, atau chord progression", "isCorrect": true}, {"text": "Harus perfect dari awal", "isCorrect": false}, {"text": "Copy lagu lain", "isCorrect": false}, {"text": "No planning", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 1, 'Apa rhyme scheme paling sederhana?', '[{"text": "AABB (couplet)", "isCorrect": true}, {"text": "ABCDEFGH", "isCorrect": false}, {"text": "No rhyme", "isCorrect": false}, {"text": "Random rhyme", "isCorrect": false}]'::jsonb, true);

-- SONGWRITING - INTERMEDIATE TIER (add 8 more for total 10)
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('songwriting', 'songwriting', 'songwriting', 2, 'Bagaimana develop song concept?', '[{"text": "Start dengan central idea dan expand organically", "isCorrect": true}, {"text": "No concept needed", "isCorrect": false}, {"text": "Copy other songs", "isCorrect": false}, {"text": "Random writing", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 2, 'Apa teknik untuk overcoming writer block?', '[{"text": "Change environment, freewrite, collaborate", "isCorrect": true}, {"text": "Force creativity", "isCorrect": false}, {"text": "Give up", "isCorrect": false}, {"text": "Copy others", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 2, 'Bagaimana menggunakan metaphor efektif?', '[{"text": "Connect concrete image dengan abstract emotion", "isCorrect": true}, {"text": "Random comparisons", "isCorrect": false}, {"text": "Literal only", "isCorrect": false}, {"text": "Overly complex", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 2, 'Apa prinsip dari melody writing?', '[{"text": "Balance antara repetition dan variation", "isCorrect": true}, {"text": "Always different", "isCorrect": false}, {"text": "Always same", "isCorrect": false}, {"text": "No pattern", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 2, 'Bagaimana create tension dan release dalam lagu?', '[{"text": "Build up dengan chord progression dan dynamics", "isCorrect": true}, {"text": "Flat dynamics", "isCorrect": false}, {"text": "Random changes", "isCorrect": false}, {"text": "No dynamics", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 2, 'Apa fungsi dari pre-chorus?', '[{"text": "Build anticipation menuju chorus", "isCorrect": true}, {"text": "Same sebagai verse", "isCorrect": false}, {"text": "End song", "isCorrect": false}, {"text": "No purpose", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 2, 'Bagaimana collaborate dengan co-writer?', '[{"text": "Open communication dan respect ideas", "isCorrect": true}, {"text": "Dictate everything", "isCorrect": false}, {"text": "No communication", "isCorrect": false}, {"text": "Reject all ideas", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 2, 'Bagaimana revise song effectively?', '[{"text": "Objective listening dan willingness to cut parts", "isCorrect": true}, {"text": "Never revise", "isCorrect": false}, {"text": "Change everything", "isCorrect": false}, {"text": "No evaluation", "isCorrect": false}]'::jsonb, true);

-- SONGWRITING - ADVANCED TIER (add 9 more for total 10)
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('songwriting', 'songwriting', 'songwriting', 3, 'Bagaimana craft lyric dengan multiple layers meaning?', '[{"text": "Ambiguity dengan specific imagery", "isCorrect": true}, {"text": "Literal only", "isCorrect": false}, {"text": "Confusing lyrics", "isCorrect": false}, {"text": "No meaning", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 3, 'Bagaimana develop unique melodic identity?', '[{"text": "Study influences sambil find personal voice", "isCorrect": true}, {"text": "Copy directly", "isCorrect": false}, {"text": "Random melodies", "isCorrect": false}, {"text": "Avoid influences", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 3, 'Apa teknik untuk writing bridge yang impactful?', '[{"text": "New perspective atau emotional shift", "isCorrect": true}, {"text": "Repeat chorus", "isCorrect": false}, {"text": "Random section", "isCorrect": false}, {"text": "No bridge", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 3, 'Bagaimana menggunakan prosody dalam lyric?', '[{"text": "Match lyric stress dengan melodic emphasis", "isCorrect": true}, {"text": "Ignore natural speech", "isCorrect": false}, {"text": "Random placement", "isCorrect": false}, {"text": "No consideration", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 3, 'Bagaimana handle revision feedback?', '[{"text": "Listen objectively dan consider merits", "isCorrect": true}, {"text": "Reject all feedback", "isCorrect": false}, {"text": "Accept everything blindly", "isCorrect": false}, {"text": "No feedback", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 3, 'Apa teknik untuk creating memorable pre-chorus?', '[{"text": "Dynamic build dengan tension increase", "isCorrect": true}, {"text": "Same as verse", "isCorrect": false}, {"text": "Random section", "isCorrect": false}, {"text": "Skip it", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 3, 'Bagaimana balance simplicity dan sophistication?', '[{"text": "Accessible surface dengan subtle complexity", "isCorrect": true}, {"text": "Overly simple", "isCorrect": false}, {"text": "Overly complex", "isCorrect": false}, {"text": "No balance", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 3, 'Bagaimana write untuk specific vocalist?', '[{"text": "Consider range, tone, dan strengths", "isCorrect": true}, {"text": "Ignore vocalist", "isCorrect": false}, {"text": "Impossible range", "isCorrect": false}, {"text": "Generic approach", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 3, 'Apa prinsip dari reharmonization?', '[{"text": "Alternative chords maintain melody sambil add color", "isCorrect": true}, {"text": "Random chords", "isCorrect": false}, {"text": "Always same chords", "isCorrect": false}, {"text": "No harmony", "isCorrect": false}]'::jsonb, true);

-- SONGWRITING - MASTER TIER (add 9 more for total 10)
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('songwriting', 'songwriting', 'songwriting', 4, 'Bagaimana craft songs dengan longevity?', '[{"text": "Timeless themes dengan quality craftsmanship", "isCorrect": true}, {"text": "Follow trends only", "isCorrect": false}, {"text": "Ignore quality", "isCorrect": false}, {"text": "No consideration", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 4, 'Bagaimana develop signature songwriting style?', '[{"text": "Consistent practice dengan authentic expression", "isCorrect": true}, {"text": "Copy successful writers", "isCorrect": false}, {"text": "Random approaches", "isCorrect": false}, {"text": "No style", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 4, 'Apa teknik untuk writing protest/message songs?', '[{"text": "Clear message dengan artful delivery", "isCorrect": true}, {"text": "Preachy lyrics", "isCorrect": false}, {"text": "No message", "isCorrect": false}, {"text": "Confusing metaphors", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 4, 'Bagaimana analyze successful songs untuk learning?', '[{"text": "Deconstruct structure, lyrics, melody, production", "isCorrect": true}, {"text": "Just listen", "isCorrect": false}, {"text": "Copy directly", "isCorrect": false}, {"text": "No analysis", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 4, 'Bagaimana write songs untuk sync licensing?', '[{"text": "Universal themes, clear mood, production-ready", "isCorrect": true}, {"text": "Overly specific", "isCorrect": false}, {"text": "Demo quality", "isCorrect": false}, {"text": "No consideration", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 4, 'Apa prinsip dari concept album creation?', '[{"text": "Unified theme dengan narrative arc", "isCorrect": true}, {"text": "Random songs", "isCorrect": false}, {"text": "No connection", "isCorrect": false}, {"text": "Singles only", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 4, 'Bagaimana mentor aspiring songwriters?', '[{"text": "Encourage authentic voice dengan technical guidance", "isCorrect": true}, {"text": "Impose your style", "isCorrect": false}, {"text": "No guidance", "isCorrect": false}, {"text": "Harsh criticism", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 4, 'Bagaimana adapt songs untuk different genres?', '[{"text": "Understand genre conventions sambil maintain core", "isCorrect": true}, {"text": "Force same arrangement", "isCorrect": false}, {"text": "Complete rewrite", "isCorrect": false}, {"text": "No adaptation", "isCorrect": false}]'::jsonb, true),
('songwriting', 'songwriting', 'songwriting', 4, 'Apa strategi untuk sustainable songwriting career?', '[{"text": "Consistent output, networking, multiple revenue streams", "isCorrect": true}, {"text": "One hit wonder mentality", "isCorrect": false}, {"text": "No strategy", "isCorrect": false}, {"text": "Quantity over quality", "isCorrect": false}]'::jsonb, true);