-- Insert 10 Indonesian questions per tier for Guitar - BASIC TIER
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('guitar', 'instrument', 'guitar', 1, 'Apa nama senar gitar yang paling tebal?', '[{"text": "Senar E (keenam)", "isCorrect": true}, {"text": "Senar A", "isCorrect": false}, {"text": "Senar D", "isCorrect": false}, {"text": "Senar G", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 1, 'Bagaimana posisi tangan yang benar saat memegang gitar?', '[{"text": "Ibu jari di belakang leher gitar", "isCorrect": true}, {"text": "Ibu jari di atas leher gitar", "isCorrect": false}, {"text": "Semua jari melingkar di leher", "isCorrect": false}, {"text": "Tangan menggantung bebas", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 1, 'Berapa jumlah senar standar pada gitar?', '[{"text": "4 senar", "isCorrect": false}, {"text": "5 senar", "isCorrect": false}, {"text": "6 senar", "isCorrect": true}, {"text": "7 senar", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 1, 'Apa yang dimaksud dengan fret pada gitar?', '[{"text": "Senar gitar", "isCorrect": false}, {"text": "Bagian logam di leher gitar", "isCorrect": true}, {"text": "Lubang suara", "isCorrect": false}, {"text": "Kepala gitar", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 1, 'Chord dasar apa yang paling mudah untuk pemula?', '[{"text": "Chord F", "isCorrect": false}, {"text": "Chord Bm", "isCorrect": false}, {"text": "Chord Em", "isCorrect": true}, {"text": "Chord Bb", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 1, 'Apa fungsi pick/plektrum?', '[{"text": "Menyetem gitar", "isCorrect": false}, {"text": "Memetik senar gitar", "isCorrect": true}, {"text": "Menghias gitar", "isCorrect": false}, {"text": "Membersihkan senar", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 1, 'Bagaimana cara memegang pick yang benar?', '[{"text": "Digenggam dengan lima jari", "isCorrect": false}, {"text": "Dipegang dengan ibu jari dan telunjuk", "isCorrect": true}, {"text": "Dipegang dengan tiga jari", "isCorrect": false}, {"text": "Diikat di tangan", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 1, 'Apa yang harus dilakukan sebelum bermain gitar?', '[{"text": "Menyetem gitar", "isCorrect": true}, {"text": "Mengganti senar", "isCorrect": false}, {"text": "Membersihkan gitar", "isCorrect": false}, {"text": "Mengganti pick", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 1, 'Berapa jari yang biasanya digunakan untuk menekan senar?', '[{"text": "2 jari", "isCorrect": false}, {"text": "3 jari", "isCorrect": false}, {"text": "4 jari", "isCorrect": true}, {"text": "5 jari", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 1, 'Apa nama bagian gitar tempat senar dipasang di ujung bawah?', '[{"text": "Headstock", "isCorrect": false}, {"text": "Neck", "isCorrect": false}, {"text": "Bridge", "isCorrect": true}, {"text": "Fretboard", "isCorrect": false}]'::jsonb, true);

-- Guitar - INTERMEDIATE TIER
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('guitar', 'instrument', 'guitar', 2, 'Teknik apa yang paling efektif untuk memainkan arpeggio?', '[{"text": "Strumming", "isCorrect": false}, {"text": "Fingerpicking", "isCorrect": true}, {"text": "Tapping", "isCorrect": false}, {"text": "Sliding", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 2, 'Bagaimana cara mencegah feedback pada gitar elektrik?', '[{"text": "Menjauh dari amplifier", "isCorrect": true}, {"text": "Menaikkan volume", "isCorrect": false}, {"text": "Menggunakan distorsi tinggi", "isCorrect": false}, {"text": "Mematikan tone control", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 2, 'Apa fungsi dari capo pada gitar?', '[{"text": "Mengubah nada dasar tanpa mengubah fingering", "isCorrect": true}, {"text": "Membuat senar lebih kencang", "isCorrect": false}, {"text": "Menghias gitar", "isCorrect": false}, {"text": "Mempercepat permainan", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 2, 'Teknik mana yang digunakan untuk chord barre?', '[{"text": "Satu jari menekan beberapa senar sekaligus", "isCorrect": true}, {"text": "Setiap jari menekan satu senar", "isCorrect": false}, {"text": "Menggunakan pick untuk semua senar", "isCorrect": false}, {"text": "Menggunakan kedua tangan", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 2, 'Apa yang dimaksud dengan hammer-on?', '[{"text": "Menekan senar tanpa memetik lagi", "isCorrect": true}, {"text": "Memetik senar dengan keras", "isCorrect": false}, {"text": "Menggesek senar", "isCorrect": false}, {"text": "Menekan dua senar bersamaan", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 2, 'Bagaimana cara yang benar melakukan pull-off?', '[{"text": "Melepas jari dengan menarik senar sedikit", "isCorrect": true}, {"text": "Mengangkat jari dengan cepat", "isCorrect": false}, {"text": "Memetik senar lagi", "isCorrect": false}, {"text": "Menggeser jari ke fret lain", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 2, 'Apa fungsi tone knob pada gitar elektrik?', '[{"text": "Mengatur volume", "isCorrect": false}, {"text": "Mengatur treble dan brightness", "isCorrect": true}, {"text": "Mengubah nada", "isCorrect": false}, {"text": "Menambah distorsi", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 2, 'Berapa lama idealnya berlatih gitar setiap hari?', '[{"text": "5-10 menit", "isCorrect": false}, {"text": "30-60 menit", "isCorrect": true}, {"text": "3-4 jam", "isCorrect": false}, {"text": "Sepanjang hari", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 2, 'Apa yang dimaksud dengan alternate picking?', '[{"text": "Memetik naik-turun secara bergantian", "isCorrect": true}, {"text": "Memetik semua senar sekaligus", "isCorrect": false}, {"text": "Memetik dengan dua pick", "isCorrect": false}, {"text": "Memetik dengan jari", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 2, 'Bagaimana cara membaca tablature gitar?', '[{"text": "Angka menunjukkan fret yang ditekan", "isCorrect": true}, {"text": "Angka menunjukkan jari yang digunakan", "isCorrect": false}, {"text": "Angka menunjukkan tempo", "isCorrect": false}, {"text": "Angka menunjukkan volume", "isCorrect": false}]'::jsonb, true);

-- Guitar - ADVANCED TIER
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('guitar', 'instrument', 'guitar', 3, 'Bagaimana cara menyetel intonasi gitar dengan benar?', '[{"text": "Menyesuaikan saddle di bridge", "isCorrect": true}, {"text": "Mengganti senar", "isCorrect": false}, {"text": "Memutar tuning peg", "isCorrect": false}, {"text": "Mengubah pickup height", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 3, 'Teknik fingering apa yang digunakan untuk solo gitar cepat?', '[{"text": "Economy picking", "isCorrect": true}, {"text": "Strumming pattern", "isCorrect": false}, {"text": "Open tuning", "isCorrect": false}, {"text": "Drop D", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 3, 'Bagaimana cara mencapai vibrato yang baik pada gitar?', '[{"text": "Menggerakkan senar horizontal dengan jari", "isCorrect": true}, {"text": "Menarik senar vertikal", "isCorrect": false}, {"text": "Menggeser pick cepat", "isCorrect": false}, {"text": "Menekan fret lebih keras", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 3, 'Apa kegunaan palm muting dalam permainan gitar?', '[{"text": "Menciptakan suara yang lebih terkontrol dan pendek", "isCorrect": true}, {"text": "Menambah sustain", "isCorrect": false}, {"text": "Menaikkan volume", "isCorrect": false}, {"text": "Mengubah tuning", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 3, 'Bagaimana cara melakukan sweep picking dengan efektif?', '[{"text": "Gerakan pick searah dengan perpindahan senar", "isCorrect": true}, {"text": "Memetik semua senar bersamaan", "isCorrect": false}, {"text": "Menggunakan fingerpicking", "isCorrect": false}, {"text": "Alternate picking yang sangat cepat", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 3, 'Apa fungsi dari truss rod pada gitar?', '[{"text": "Mengatur lengkungan neck gitar", "isCorrect": true}, {"text": "Mengikat senar", "isCorrect": false}, {"text": "Memperkuat body", "isCorrect": false}, {"text": "Mengatur action senar", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 3, 'Teknik tapping memerlukan koordinasi antara apa?', '[{"text": "Tangan kiri dan kanan di fretboard", "isCorrect": true}, {"text": "Kedua kaki untuk pedal", "isCorrect": false}, {"text": "Pick dan jari", "isCorrect": false}, {"text": "Mulut dan tangan", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 3, 'Bagaimana cara mencapai harmonic natural pada gitar?', '[{"text": "Menyentuh senar ringan di fret 5, 7, 12", "isCorrect": true}, {"text": "Menekan senar dengan keras", "isCorrect": false}, {"text": "Menggunakan distorsi tinggi", "isCorrect": false}, {"text": "Memetik dekat bridge", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 3, 'Apa yang dimaksud dengan string bending?', '[{"text": "Menarik senar untuk menaikkan pitch", "isCorrect": true}, {"text": "Memutar tuning peg", "isCorrect": false}, {"text": "Menggunakan capo", "isCorrect": false}, {"text": "Menekan senar lebih dalam", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 3, 'Bagaimana penggunaan delay dan reverb mempengaruhi tone gitar?', '[{"text": "Menambah kedalaman dan ruang pada suara", "isCorrect": true}, {"text": "Menaikkan volume", "isCorrect": false}, {"text": "Mengubah tuning", "isCorrect": false}, {"text": "Mengurangi noise", "isCorrect": false}]'::jsonb, true);

-- Guitar - MASTER TIER  
INSERT INTO tier_assessment_questions (instrument, category, sub_category, tier_level, question_text, options, is_production) VALUES
('guitar', 'instrument', 'guitar', 4, 'Teknik bowing lanjutan apa yang digunakan dalam performa orkestra gitar?', '[{"text": "Legato bowing dengan kontrol dinamik", "isCorrect": true}, {"text": "Strumming keras", "isCorrect": false}, {"text": "Palm muting konstan", "isCorrect": false}, {"text": "Tapping dua tangan", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 4, 'Bagaimana cara mevoicing chord gitar untuk resonansi optimal di register berbeda?', '[{"text": "Memilih inversi chord sesuai register", "isCorrect": true}, {"text": "Selalu menggunakan open chord", "isCorrect": false}, {"text": "Menggunakan power chord", "isCorrect": false}, {"text": "Menghindari bass note", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 4, 'Latihan apa yang meningkatkan independensi jari untuk gitar klasik?', '[{"text": "Etude Sor dan Villa-Lobos", "isCorrect": true}, {"text": "Power chord progression", "isCorrect": false}, {"text": "Strumming pattern", "isCorrect": false}, {"text": "Alternate tuning drill", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 4, 'Bagaimana menerapkan mode dalam improvisasi gitar jazz?', '[{"text": "Menggunakan mode yang sesuai dengan chord progression", "isCorrect": true}, {"text": "Hanya menggunakan pentatonic", "isCorrect": false}, {"text": "Menghindari alterasi", "isCorrect": false}, {"text": "Bermain chromatic scale", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 4, 'Apa prinsip utama dalam arranging gitar untuk ensemble?', '[{"text": "Menyeimbangkan voicing dan register antar gitar", "isCorrect": true}, {"text": "Semua gitar bermain unison", "isCorrect": false}, {"text": "Fokus pada lead guitar saja", "isCorrect": false}, {"text": "Menghindari harmoni", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 4, 'Bagaimana teknik hybrid picking meningkatkan fleksibilitas?', '[{"text": "Menggabungkan pick dan jari untuk pola kompleks", "isCorrect": true}, {"text": "Menggunakan dua pick", "isCorrect": false}, {"text": "Picking dengan kedua tangan", "isCorrect": false}, {"text": "Hanya fingerstyle", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 4, 'Apa pendekatan terbaik untuk mengajar teknik advanced kepada siswa?', '[{"text": "Membangun dari fundamental dengan progression bertahap", "isCorrect": true}, {"text": "Langsung mengajarkan teknik tersulit", "isCorrect": false}, {"text": "Fokus pada teori saja", "isCorrect": false}, {"text": "Menghindari latihan lambat", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 4, 'Bagaimana mengoptimalkan setup gitar untuk berbagai genre?', '[{"text": "Menyesuaikan action, pickup height, dan tone sesuai genre", "isCorrect": true}, {"text": "Setup universal untuk semua genre", "isCorrect": false}, {"text": "Hanya mengganti senar", "isCorrect": false}, {"text": "Menggunakan satu amplifier setting", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 4, 'Teknik recording gitar apa yang menghasilkan tone terbaik?', '[{"text": "Mikropon placement dan room acoustics", "isCorrect": true}, {"text": "Recording langsung ke line in", "isCorrect": false}, {"text": "Maksimalkan gain", "isCorrect": false}, {"text": "Gunakan semua efek sekaligus", "isCorrect": false}]'::jsonb, true),
('guitar', 'instrument', 'guitar', 4, 'Bagaimana menganalisis dan mereproduksi tone gitaris profesional?', '[{"text": "Mengidentifikasi gear, teknik, dan EQ yang digunakan", "isCorrect": true}, {"text": "Meniru tanpa analisis", "isCorrect": false}, {"text": "Hanya membeli gear yang sama", "isCorrect": false}, {"text": "Menggunakan preset digital", "isCorrect": false}]'::jsonb, true);