-- Insert a dummy event for testing lottery system
INSERT INTO public.events (
  title,
  description,
  date,
  start_time,
  end_time,
  location,
  address,
  price,
  max_capacity,
  current_registrations,
  organizer_id,
  banner_image_url,
  speaker_name,
  speaker_bio,
  speaker_image_url,
  google_maps_link,
  registration_deadline,
  cancellation_deadline,
  allow_cancellation,
  status
) VALUES (
  'Worship Night & Music Workshop',
  'Join us for an inspiring evening of worship music and learn professional arrangement techniques. This event includes live performances, interactive workshops, and networking with fellow musicians.',
  '2025-02-15',
  '19:00:00',
  '22:00:00',
  'Jakarta Music Center',
  'Jl. Sudirman No. 123, Jakarta Pusat, DKI Jakarta 10110',
  150000,
  200,
  0,
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
  'David Chen',
  'David Chen is a renowned worship leader and music arranger with over 15 years of experience. He has led worship at major conferences and has arranged music for several contemporary Christian artists.',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
  'https://maps.google.com/?q=Jakarta+Music+Center+Sudirman',
  '2025-02-14 23:59:59',
  '2025-02-14 12:00:00',
  true,
  'active'
);