// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from "@supabase/supabase-js";
// import type { Database } from './types'; // Disabled: using untyped client to avoid missing types in local builds

// Environment detection based on hostname
const getSupabaseConfig = () => {
  const hostname =
    typeof window !== "undefined" ? window.location.hostname : "";
  const isProduction =
    hostname === "arrangely.io" || hostname === "www.arrangely.io";
  const isStaging = hostname === "staging.arrangely.io";

  if (isProduction) {
  return {
    url: "https://api.arrangely.io",
    key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtc2V5cmNveGJ3aHp0dnZpdmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzM0MzksImV4cCI6MjA3NDMwOTQzOX0.gbU9MmiwsVbrEz6ehY7KJnWrURmA1tKBxFlJXAmNmgA",
  };
  } else if (isStaging) {
    return {
      url: "https://jowuhdfznveuopeqwzzd.supabase.co",
      key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvd3VoZGZ6bnZldW9wZXF3enpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjEyMjMsImV4cCI6MjA2ODgzNzIyM30.KFMkZdBXK5X-LY0r8xreRe2CxvkC3G1o9lFq_ZTeZ8A",
    };
    //   //   // Development/staging environment (all use same production database with is_production field)
    //   // Development/staging environment (all use same production database with is_production field)
  } else {
    return {
      url: "https://jowuhdfznveuopeqwzzd.supabase.co",
      key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvd3VoZGZ6bnZldW9wZXF3enpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjEyMjMsImV4cCI6MjA2ODgzNzIyM30.KFMkZdBXK5X-LY0r8xreRe2CxvkC3G1o9lFq_ZTeZ8A",
    };
  }
};

const config = getSupabaseConfig();

// Create the base Supabase client (untyped to avoid missing local types)
const baseClient = createClient(config.url, config.key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Simple wrapper for Supabase client (no rate limit)
class WrappedSupabaseClient {
  private client: any;

  constructor(client: any) {
    this.client = client;
  }

  // Proxy client properties and methods directly
  get auth() {
    return this.client.auth;
  }
  get storage() {
    return this.client.storage;
  }
  get realtime() {
    return this.client.realtime;
  }
  get functions() {
    return this.client.functions;
  }

  from(table: string) {
    return this.client.from(table);
  }

  rpc(fnName: string, params?: any, options?: any) {
    return this.client.rpc(fnName, params, options);
  }

  channel(name: string, opts?: any) {
    return this.client.channel(name, opts);
  }

  removeChannel(channel: any) {
    return this.client.removeChannel(channel);
  }

  removeAllChannels() {
    return this.client.removeAllChannels();
  }

  getChannels() {
    return this.client.getChannels();
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const SUPABASE_URL = config.url;
export const SUPABASE_ANON_KEY = config.key;
export const supabase = new WrappedSupabaseClient(baseClient);
